// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyihajkjfslygzuvbqnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5aWhhamtqZnNseWd6dXZicW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODE2MzgsImV4cCI6MjA2MjY1NzYzOH0.yAnRxTLp5-FmXQYge_Phg5TyHUrDwDNJgFGbWdB5PsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);